version: '3.8'

services:
  # 1. FRONTEND
  frontend:
    build:
      context: ../../web/frontend
      dockerfile: Dockerfile
    container_name: iot_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - ingestion-service
      - chat-service
    networks:
      - iot-network

  # 2. DATABASE (TimescaleDB)
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: iot_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=iot_fleet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d iot_fleet_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. REDIS (Cache & Stream)
  redis:
    image: redis:alpine
    container_name: iot_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - iot-network

  # 4. BACKEND SERVICES
  ingestion-service:
    build:
      context: ../../
      dockerfile: web/backend/services/ingestion-service/Dockerfile
    container_name: iot_ingestion
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    depends_on:
      - redis
    networks:
      - iot-network

  processor-service:
    build:
      context: ../../
      dockerfile: web/backend/services/processor-service/Dockerfile
    container_name: iot_processor
    restart: always
    environment:
      - REDIS_ADDR=redis:6379
      - DATABASE_URL=postgres://admin:secretpassword@timescaledb:5432/iot_fleet_db?sslmode=disable
    depends_on:
      - redis
      - timescaledb
    networks:
      - iot-network

  chat-service:
    build:
      context: ../../
      dockerfile: web/backend/services/chat-service/Dockerfile
    container_name: iot_chat
    restart: always
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      - iot-network

  simulation-service:
    build:
      context: ../../web/backend/services/simulation-service
      dockerfile: Dockerfile
    container_name: iot_simulation
    restart: always
    environment:
      - INGESTION_URL=http://ingestion-service:8080/api/telemetry
      - NUM_VEHICLES=5
    depends_on:
      - ingestion-service
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  postgres_data:
