services:
  web_proxy:
    image: nginx:alpine
    ports:
      - "8080:443"
      - "8081:80"
    volumes:
      - ../../web/public:/usr/share/nginx/html
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../ssl/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro
      - ../ssl/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro

  # 2. DATABASE (TimescaleDB)

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: iot_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=iot_fleet_db
    ports:
      - "5432:5432"
    volumes:
      - ../../data/postgres_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    networks:
      - iot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d iot_fleet_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 3. REDIS (Cache & Stream)

  redis:
    image: redis:alpine
    container_name: iot_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - iot-network

  # 4. BACKEND SERVISLER (Go)

  processor-service:
    build:
      context: ../../services/processor
    container_name: iot_processor
    restart: on-failure
    depends_on:
      timescaledb:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_DSN=postgres://admin:secretpassword@timescaledb:5432/iot_fleet_db?sslmode=disable
      - REDIS_ADDR=redis:6379
      - ENV=docker
    volumes:
      - ../../data/logs:/root/logs
    networks:
      - iot-network

  ingestion-service:
    build:
      context: ../../services/ingestion
    container_name: iot_ingestion
    restart: on-failure
    depends_on:
      redis:
        condition: service_started
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - ../../data/logs:/root/logs
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge